# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: weatherapi-adm@met.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.forecast_time_step_data_next1_hours import ForecastTimeStepDataNext1Hours  # noqa: E501
from swagger_client.rest import ApiException


class TestForecastTimeStepDataNext1Hours(unittest.TestCase):
    """ForecastTimeStepDataNext1Hours unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForecastTimeStepDataNext1Hours(self):
        """Test ForecastTimeStepDataNext1Hours"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.forecast_time_step_data_next1_hours.ForecastTimeStepDataNext1Hours()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
