# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: weatherapi-adm@met.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_api import DataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_classic_format_get(self):
        """Test case for classic_format_get

        """
        pass

    def test_classic_get(self):
        """Test case for classic_get

        """
        pass

    def test_compact_format_get(self):
        """Test case for compact_format_get

        """
        pass

    def test_compact_get(self):
        """Test case for compact_get

        """
        pass

    def test_complete_format_get(self):
        """Test case for complete_format_get

        """
        pass

    def test_complete_get(self):
        """Test case for complete_get

        """
        pass

    def test_status_format_get(self):
        """Test case for status_format_get

        """
        pass

    def test_status_get(self):
        """Test case for status_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
