# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: weatherapi-adm@met.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.point_geometry import PointGeometry  # noqa: E501
from swagger_client.rest import ApiException


class TestPointGeometry(unittest.TestCase):
    """PointGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointGeometry(self):
        """Test PointGeometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.point_geometry.PointGeometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
