# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: weatherapi-adm@met.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForecastTimeStepDataNext6Hours(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'details': 'ForecastTimePeriod',
        'summary': 'ForecastSummary'
    }

    attribute_map = {
        'details': 'details',
        'summary': 'summary'
    }

    def __init__(self, details=None, summary=None):  # noqa: E501
        """ForecastTimeStepDataNext6Hours - a model defined in Swagger"""  # noqa: E501
        self._details = None
        self._summary = None
        self.discriminator = None
        self.details = details
        self.summary = summary

    @property
    def details(self):
        """Gets the details of this ForecastTimeStepDataNext6Hours.  # noqa: E501


        :return: The details of this ForecastTimeStepDataNext6Hours.  # noqa: E501
        :rtype: ForecastTimePeriod
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this ForecastTimeStepDataNext6Hours.


        :param details: The details of this ForecastTimeStepDataNext6Hours.  # noqa: E501
        :type: ForecastTimePeriod
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details

    @property
    def summary(self):
        """Gets the summary of this ForecastTimeStepDataNext6Hours.  # noqa: E501


        :return: The summary of this ForecastTimeStepDataNext6Hours.  # noqa: E501
        :rtype: ForecastSummary
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this ForecastTimeStepDataNext6Hours.


        :param summary: The summary of this ForecastTimeStepDataNext6Hours.  # noqa: E501
        :type: ForecastSummary
        """
        if summary is None:
            raise ValueError("Invalid value for `summary`, must not be `None`")  # noqa: E501

        self._summary = summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForecastTimeStepDataNext6Hours, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForecastTimeStepDataNext6Hours):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
