# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: weatherapi-adm@met.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForecastSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'symbol_code': 'WeatherSymbol'
    }

    attribute_map = {
        'symbol_code': 'symbol_code'
    }

    def __init__(self, symbol_code=None):  # noqa: E501
        """ForecastSummary - a model defined in Swagger"""  # noqa: E501
        self._symbol_code = None
        self.discriminator = None
        self.symbol_code = symbol_code

    @property
    def symbol_code(self):
        """Gets the symbol_code of this ForecastSummary.  # noqa: E501


        :return: The symbol_code of this ForecastSummary.  # noqa: E501
        :rtype: WeatherSymbol
        """
        return self._symbol_code

    @symbol_code.setter
    def symbol_code(self, symbol_code):
        """Sets the symbol_code of this ForecastSummary.


        :param symbol_code: The symbol_code of this ForecastSummary.  # noqa: E501
        :type: WeatherSymbol
        """
        if symbol_code is None:
            raise ValueError("Invalid value for `symbol_code`, must not be `None`")  # noqa: E501

        self._symbol_code = symbol_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForecastSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForecastSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
